package com.liu.ljwallet.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.liu.ljwallet.entity.MyWallet;
import com.liu.ljwallet.entity.Transaction;

import com.liu.ljwallet.db.MyWalletDao;
import com.liu.ljwallet.db.TransactionDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig myWalletDaoConfig;
    private final DaoConfig transactionDaoConfig;

    private final MyWalletDao myWalletDao;
    private final TransactionDao transactionDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        myWalletDaoConfig = daoConfigMap.get(MyWalletDao.class).clone();
        myWalletDaoConfig.initIdentityScope(type);

        transactionDaoConfig = daoConfigMap.get(TransactionDao.class).clone();
        transactionDaoConfig.initIdentityScope(type);

        myWalletDao = new MyWalletDao(myWalletDaoConfig, this);
        transactionDao = new TransactionDao(transactionDaoConfig, this);

        registerDao(MyWallet.class, myWalletDao);
        registerDao(Transaction.class, transactionDao);
    }
    
    public void clear() {
        myWalletDaoConfig.clearIdentityScope();
        transactionDaoConfig.clearIdentityScope();
    }

    public MyWalletDao getMyWalletDao() {
        return myWalletDao;
    }

    public TransactionDao getTransactionDao() {
        return transactionDao;
    }

}
